// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ujEVTe3CdPBNJ5rENaGJHTMakmzpQqo',
    appId: '1:245818385038:web:07bf80fd6e124da3bbdfdf',
    messagingSenderId: '245818385038',
    projectId: 'cell-notation-app',
    authDomain: 'cell-notation-app.firebaseapp.com',
    storageBucket: 'cell-notation-app.firebasestorage.app',
    measurementId: 'G-K1F3790MF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMB9ImH95sYczTOgm-dYUx_uf-_1evWk',
    appId: '1:245818385038:android:ffbbd21ba2df12a9bbdfdf',
    messagingSenderId: '245818385038',
    projectId: 'cell-notation-app',
    storageBucket: 'cell-notation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgJ18C5pxMLLfPK2eLsx8AQHZG0DQDcAg',
    appId: '1:245818385038:ios:6062be14b6fc7240bbdfdf',
    messagingSenderId: '245818385038',
    projectId: 'cell-notation-app',
    storageBucket: 'cell-notation-app.firebasestorage.app',
    iosBundleId: 'com.example.cellNotationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgJ18C5pxMLLfPK2eLsx8AQHZG0DQDcAg',
    appId: '1:245818385038:ios:6062be14b6fc7240bbdfdf',
    messagingSenderId: '245818385038',
    projectId: 'cell-notation-app',
    storageBucket: 'cell-notation-app.firebasestorage.app',
    iosBundleId: 'com.example.cellNotationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ujEVTe3CdPBNJ5rENaGJHTMakmzpQqo',
    appId: '1:245818385038:web:b4764498b06f7d78bbdfdf',
    messagingSenderId: '245818385038',
    projectId: 'cell-notation-app',
    authDomain: 'cell-notation-app.firebaseapp.com',
    storageBucket: 'cell-notation-app.firebasestorage.app',
    measurementId: 'G-EEZG2SEV7J',
  );
}
